# Processamento Filtro 05

Este notebook realiza o pré-processamento da base de dados filter05.csv, preparando os dados para análise. O pipeline utiliza scripts organizados na pasta src/ e segue etapas bem definidas para garantir reprodutibilidade, clareza e organização dos dados processados.

## 1. Configuração do Ambiente e Importação de Bibliotecas

Ajuste do ambiente para importar módulos do diretório `src/` e importação das bibliotecas necessárias.

In [17]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..', 'src')))

import pandas as pd
import numpy as np

## 2. Carregamento e Inspeção Inicial dos Dados

Utilizando o módulo de carregamento para ler o arquivo de dados e exibir informações iniciais.

In [18]:
from load_data import load_and_inspect

data_path = os.path.join('..', 'data', 'filtro05.csv')
df = load_and_inspect(data_path)
df.head()

Shape: (13, 55)
Head:
                                                  0  1   \
0  FILTRO 05: Artigos que tem como cenário de apl...
1                     QUATIDADE TOTAL DE ARTIGOS: 29
2                        QUANTIDADE DE REMOVIDOS: 22
3  Anotação: Alguns itens aparecem tanto em Parâm...
4

                                     2  3  4  5   \
0
1
2
3
4                   Comunicação de Rede

                                            6  7  8  9   ... 45 46 47 48 49  \
0                                                        ...
1                                                        ...
2                                                        ...
3                                                        ...
4  Especificação do Monitoramento de Pacientes           ...

                  50 51 52                  53 54
0
1
2
3
4  Paramêtros de Qos        Parâmetros de Rede

[5 rows x 55 columns]
Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 55 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       13 non-null     object
 1   1       13 non-null     object
 2   2       13 non-null     object
 3   3       13 non-null     object
 4   4       13 non-null     object
 5   5       13 non-null     object
 6   6       13 non-null     object
 7   7       13 non-null     object
 8   8       13 non-null     object
 9   9       13 non-null     object
 10  10      13 non-null     object
 11  11      13 non-null     object
 12  12      13 non-null     object
 13  13      13 non-null     object
 14  14      13 non-null     object
 15  15      13 non-null     object
 16  16      13 non-null     object
 17  17      13 non-null     object
 18  18      13 non-null     object
 19  19      13 non-null     object
 20  20      13 non-null     object
 21  21      13 non-null     object
 22  22      13 non-null     object
 23  23      13 non-null     object
 24  24      13 non-null     object
 25  25      13 non-null     object
 26  26      13 non-null     object
 27  27      13 non-null     object
 28  28      13 non-null     object
 29  29      13 non-null     object
 30  30      13 non-null     object
 31  31      13 non-null     object
 32  32      13 non-null     object
 33  33      13 non-null     object
 34  34      13 non-null     object
 35  35      13 non-null     object
 36  36      13 non-null     object
 37  37      13 non-null     object
 38  38      13 non-null     object
 39  39      13 non-null     object
 40  40      13 non-null     object
 41  41      13 non-null     object
 42  42      13 non-null     object
 43  43      13 non-null     object
 44  44      13 non-null     object
 45  45      13 non-null     object
 46  46      13 non-null     object
 47  47      13 non-null     object
 48  48      13 non-null     object
 49  49      13 non-null     object
 50  50      13 non-null     object
 51  51      13 non-null     object
 52  52      13 non-null     object
 53  53      13 non-null     object
 54  54      13 non-null     object
dtypes: object(55)
memory usage: 5.7+ KB
None

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,FILTRO 05: Artigos que tem como cenário de apl...,,,,,,,,,,...,,,,,,,,,,
1,QUATIDADE TOTAL DE ARTIGOS: 29,,,,,,,,,,...,,,,,,,,,,
2,QUANTIDADE DE REMOVIDOS: 22,,,,,,,,,,...,,,,,,,,,,
3,Anotação: Alguns itens aparecem tanto em Parâm...,,,,,,,,,,...,,,,,,,,,,
4,,,Comunicação de Rede,,,,Especificação do Monitoramento de Pacientes,,,,...,,,,,,Paramêtros de Qos,,,Parâmetros de Rede,

## 3. Limpeza e Pré-processamento da Base de Dados

Esta etapa remove as 5 primeiras linhas, ajusta o cabeçalho e trata valores ausentes ou substituições específicas (como "X" por 1), garantindo que os dados estejam prontos para análise.

In [19]:
from clean_data import clean_data
df = clean_data(df)
df.head()

,Title,Protocolo,Tipo (Síncrona/Assíncrona),Transmissão de dados em tempo real,Padrão de comunicação,Parâmetro Monitorado,Contexto de Monitoramento,Características do Monitoramento,Local de Monitoramento,Linguagem de Programação,...,Latência fim a fim,RTT (Round Trip Time),Packet Delay Budget (PDB),Tempo de Resposta,Jitter,Throughput,Taxa de perda de pacotes,Disponibilidade da Rede,Frequência de Operação,Largura de banda do link
0,Towards a European Health Data Slice,"UDP, HTTP",Não Especificado,Sim,5G SA,"eletrocardiograma (ECG), saturação de oxigênio...",remoto,"tempo real, contínuo","hospital, residência, instalações de cuidados ...",Python,...,Não especificado,None,None,None,None,160 Mbps (DL); 80 Mbps (UL),None,≈100%,3.5 GHz,70 MHz
1,AI-Driven Data Analytics and Intent-Based Netw...,None,Não Especificado,Sim,B5G,None,None,automático,None,"Python, Java",...,Não especificado,None,None,None,5ms (IoT); 7.1ms (eMBB),200 Mbps (IoT); 136 Mbps (eMBB); 72 Mbps (URLLC),None,None,Não especificado,None
2,FRADIS: A Machine Learning-based Multipath Sol...,"MPTCP, uMPTCP",Não Especificado,Sim,5G,None,None,"adaptativo, tempo real",None,None,...,None,1000–1120 ms,None,None,None,None,None,None,None,None
3,An Evaluation of e-Health Service Performance ...,None,Não Especificado,Sim,5G,"sinais vitais, frequência cardíaca, temperatur...",remoto,"tempo real, contínuo","hospital, residência",None,...,Não especificado,None,None,0.22 a 1.28 ms,None,Não especificado,None,None,Não especificado,Não especificado
4,Large-scale trialing of the B5G technology for...,None,Não Especificado,Sim,5G NSA,"sinais vitais, frequência cardíaca, saturação ...",remoto,"tempo real, contínuo, mobilidade","campo, ambulância, hospital, local lotado",None,...,Não especificado,None,None,None,None,Não especificado,None,None,3.5 GHz,80-100 MHz

## 4. Tratamento de Múltiplos Valores em Células

Separação de valores por ';', remoção de espaços extras e padronização dos termos para análise de frequência.

In [20]:
from transform_data import transform_multivalue_cells, explode_and_count

df = transform_multivalue_cells(df)
freq_tables = explode_and_count(df)
freq_tables[list(freq_tables.keys())[0]].head()

                                                    count
Title
Towards a european health data slice                    1
Ai-driven data analytics and intent-based netwo...      1
Fradis: a machine learning-based multipath solu...      1
An evaluation of e-health service performance t...      1
Large-scale trialing of the b5g technology for ...      1

## 5. Normalização de Dados Numéricos

Identificação automática das colunas numéricas e aplicação de Min-Max Scaling (ou Z-score) apenas nessas colunas.

In [21]:
from normalize_data import normalize_columns

df = normalize_columns(df, method='minmax')
df.head()

,Title,Protocolo,Tipo (Síncrona/Assíncrona),Transmissão de dados em tempo real,Padrão de comunicação,Parâmetro Monitorado,Contexto de Monitoramento,Características do Monitoramento,Local de Monitoramento,Linguagem de Programação,...,Latência fim a fim,RTT (Round Trip Time),Packet Delay Budget (PDB),Tempo de Resposta,Jitter,Throughput,Taxa de perda de pacotes,Disponibilidade da Rede,Frequência de Operação,Largura de banda do link
0,Towards a european health data slice,"Udp, http",Não especificado,Sim,5g sa,"Eletrocardiograma (ecg), saturação de oxigênio...",Remoto,"Tempo real, contínuo","Hospital, residência, instalações de cuidados ...",Python,...,Não especificado,None,None,None,None,160 mbps (dl);80 mbps (ul),None,≈100%,3.5 ghz,70 mhz
1,Ai-driven data analytics and intent-based netw...,None,Não especificado,Sim,B5g,None,None,Automático,None,"Python, java",...,Não especificado,None,None,None,5ms (iot);7.1ms (embb),200 mbps (iot);136 mbps (embb);72 mbps (urllc),None,None,Não especificado,None
2,Fradis: a machine learning-based multipath sol...,"Mptcp, umptcp",Não especificado,Sim,5g,None,None,"Adaptativo, tempo real",None,None,...,None,1000–1120 ms,None,None,None,None,None,None,None,None
3,An evaluation of e-health service performance ...,None,Não especificado,Sim,5g,"Sinais vitais, frequência cardíaca, temperatur...",Remoto,"Tempo real, contínuo","Hospital, residência",None,...,Não especificado,None,None,0.22 a 1.28 ms,None,Não especificado,None,None,Não especificado,Não especificado
4,Large-scale trialing of the b5g technology for...,None,Não especificado,Sim,5g nsa,"Sinais vitais, frequência cardíaca, saturação ...",Remoto,"Tempo real, contínuo, mobilidade","Campo, ambulância, hospital, local lotado",None,...,Não especificado,None,None,None,None,Não especificado,None,None,3.5 ghz,80-100 mhz

## 6. Exportação do Dataset Processado

Salvando o DataFrame final processado na pasta `data/` como `data_processado.csv`.

In [22]:
output_path = os.path.join('..', 'data', 'filtro05_processado.csv')
df.to_csv(output_path, index=False)
print(f"Arquivo processado salvo em: {output_path}")

Arquivo processado salvo em: ..\data\filtro05_processado.csv