# Processamento Filtro 04

Este notebook realiza o pré-processamento da base de dados filter04.csv, preparando os dados para análise. O pipeline utiliza scripts organizados na pasta src/ e segue etapas bem definidas para garantir reprodutibilidade, clareza e organização dos dados processados.

## 1. Configuração do Ambiente e Importação de Bibliotecas

Ajuste do ambiente para importar módulos do diretório `src/` e importação das bibliotecas necessárias.

In [1]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..', 'src')))

import pandas as pd
import numpy as np

## 2. Carregamento e Inspeção Inicial dos Dados

Utilizando o módulo de carregamento para ler o arquivo de dados e exibir informações iniciais.

In [2]:
from load_data import load_and_inspect

data_path = os.path.join('..', 'data', 'filtro04.csv')
df = load_and_inspect(data_path)
df.head()

Shape: (35, 36)
Head:
                                                  0  1  2   \
0  FILTRO 04: Extração de características da solu...
1                     QUATIDADE TOTAL DE ARTIGOS: 29
2                          QUANTIDADE DE REMOVIDOS:
3  Anotação: “Contexto geral de e-Health” é utili...
4

                    3  4  5   \
0
1
2
3
4  Tipo de Arquitetura

                                                  6  7  8   \
0
1
2
3
4                                                ...

                                                  9   ... 26 27  \
0                                                     ...
1                                                     ...
2                                                     ...
3                                                     ...
4                                 Dinamicidade do...  ...

                        28 29 30 31                                 32 33 34  \
0
1
2
3
4  Abordagem de Otimização                  Artefato de código e dados

  35
0
1
2
3
4

[5 rows x 36 columns]
Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 36 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       35 non-null     object
 1   1       35 non-null     object
 2   2       35 non-null     object
 3   3       35 non-null     object
 4   4       35 non-null     object
 5   5       35 non-null     object
 6   6       35 non-null     object
 7   7       35 non-null     object
 8   8       35 non-null     object
 9   9       35 non-null     object
 10  10      35 non-null     object
 11  11      35 non-null     object
 12  12      35 non-null     object
 13  13      35 non-null     object
 14  14      35 non-null     object
 15  15      35 non-null     object
 16  16      35 non-null     object
 17  17      35 non-null     object
 18  18      35 non-null     object
 19  19      35 non-null     object
 20  20      35 non-null     object
 21  21      35 non-null     object
 22  22      35 non-null     object
 23  23      35 non-null     object
 24  24      35 non-null     object
 25  25      35 non-null     object
 26  26      35 non-null     object
 27  27      35 non-null     object
 28  28      35 non-null     object
 29  29      35 non-null     object
 30  30      35 non-null     object
 31  31      35 non-null     object
 32  32      35 non-null     object
 33  33      35 non-null     object
 34  34      35 non-null     object
 35  35      35 non-null     object
dtypes: object(36)
memory usage: 10.0+ KB
None

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,FILTRO 04: Extração de características da solu...,,,,,,,,,,...,,,,,,,,,,
1,QUATIDADE TOTAL DE ARTIGOS: 29,,,,,,,,,,...,,,,,,,,,,
2,QUANTIDADE DE REMOVIDOS:,,,,,,,,,,...,,,,,,,,,,
3,Anotação: “Contexto geral de e-Health” é utili...,,,,,,,,,,...,,,,,,,,,,
4,,,,Tipo de Arquitetura,,,...,,,Dinamicidade do...,...,,,Abordagem de Otimização,,,,Artefato de código e dados,,,

## 3. Limpeza e Pré-processamento da Base de Dados

Esta etapa remove as 5 primeiras linhas, ajusta o cabeçalho e trata valores ausentes ou substituições específicas (como "X" por 1), garantindo que os dados estejam prontos para análise.

In [3]:
from clean_data import clean_data
df = clean_data(df)
df.head()

c:\Users\crist\OneDrive\Documentos\VSCODE\VSCODE7PERIODO\EHEALTH\artigo1\eHealth-Artigo-I\src\clean_data.py:20: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("X", 1)

,Title,Centralizado,Descentralizado,Distribuído,Hierárquico,Multidomínio,Paradigma Computacional,Técnica Computacional,Cenário de Aplicação,Estático,...,Usa Otimização,Abordagem,Família de Otimização,Subtipo de Metaheurística,Algoritmo Específico,Possui Link,Tipo do Artefato,Plataforma,URL,
0,Latency-Aware Network Slicing for 5G URLLC App...,1,0,0,0,0,Sistemas Baseados em Agentes,Reinforcement Learning,Cirurgia remota; Telemedicina,0,...,Não,None,None,None,None,Não,None,None,None,0
1,Towards a European Health Data Slice,0,0,1,0,0,Computação em Névoa,Criptografia,Monitoramento de pacientes; Compartilhamento d...,0,...,Não,None,None,None,None,Não,None,None,None,0
2,A Self-Manageable Network Infrastructure Towar...,1,0,1,1,0,Computação Orientada a Serviços,Reinforcement Learning,Ambulância conectada,0,...,Não,None,None,None,None,Não,Contatar os autores,Contatar os autores,Contatar os autores,0
3,AI-Driven Data Analytics and Intent-Based Netw...,1,0,0,0,1,Computação Orientada a Serviços,Machine Learning,Contexto geral de e-Health,0,...,Não,None,None,None,None,Sim,Dataset,Website; GitHub,http://gwa.ewi.tudelft.nl/datasets/gwa-t-13-ma...,Menciona o uso de Algoritmos Genéticos (GA) pa...
4,A New Technology for Higher end Communication ...,1,0,0,0,0,Computação Orientada a Serviços,Otimização Heurística,Cirurgia remota; Telemedicina,0,...,Sim,Heurística,Greedy,None,Not Specified,Não,None,None,None,0

## 4. Tratamento de Múltiplos Valores em Células

Separação de valores por ';', remoção de espaços extras e padronização dos termos para análise de frequência.

In [4]:
from transform_data import transform_multivalue_cells, explode_and_count

df = transform_multivalue_cells(df)
freq_tables = explode_and_count(df)
freq_tables[list(freq_tables.keys())[0]].head()

                                                    count
Title
Latency-aware network slicing for 5g urllc appl...      1
Towards a european health data slice                    1
A self-manageable network infrastructure toward...      1
Ai-driven data analytics and intent-based netwo...      1
A new technology for higher end communication u...      1

## 5. Normalização de Dados Numéricos

Identificação automática das colunas numéricas e aplicação de Min-Max Scaling (ou Z-score) apenas nessas colunas.

In [5]:
from normalize_data import normalize_columns

df = normalize_columns(df, method='minmax')
df.head()

,Title,Centralizado,Descentralizado,Distribuído,Hierárquico,Multidomínio,Paradigma Computacional,Técnica Computacional,Cenário de Aplicação,Estático,...,Usa Otimização,Abordagem,Família de Otimização,Subtipo de Metaheurística,Algoritmo Específico,Possui Link,Tipo do Artefato,Plataforma,URL,
0,Latency-aware network slicing for 5g urllc app...,1,0,0,0,0,Sistemas baseados em agentes,Reinforcement learning,Cirurgia remota;Telemedicina,0,...,Não,None,None,None,None,Não,None,None,None,0
1,Towards a european health data slice,0,0,1,0,0,Computação em névoa,Criptografia,Monitoramento de pacientes;Compartilhamento de...,0,...,Não,None,None,None,None,Não,None,None,None,0
2,A self-manageable network infrastructure towar...,1,0,1,1,0,Computação orientada a serviços,Reinforcement learning,Ambulância conectada,0,...,Não,None,None,None,None,Não,Contatar os autores,Contatar os autores,Contatar os autores,0
3,Ai-driven data analytics and intent-based netw...,1,0,0,0,1,Computação orientada a serviços,Machine learning,Contexto geral de e-health,0,...,Não,None,None,None,None,Sim,Dataset,Website;Github,Http://gwa.ewi.tudelft.nl/datasets/gwa-t-13-ma...,Menciona o uso de algoritmos genéticos (ga) pa...
4,A new technology for higher end communication ...,1,0,0,0,0,Computação orientada a serviços,Otimização heurística,Cirurgia remota;Telemedicina,0,...,Sim,Heurística,Greedy,None,Not specified,Não,None,None,None,0

## 6. Exportação do Dataset Processado

Salvando o DataFrame final processado na pasta `data/` como `data_processado.csv`.

In [6]:
output_path = os.path.join('..', 'data', 'filtro04_processado.csv')
df.to_csv(output_path, index=False)
print(f"Arquivo processado salvo em: {output_path}")

Arquivo processado salvo em: ..\data\filtro04_processado.csv